// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTBg2SdgW1ImAsV9fQi3tzQYNpFIrrRY',
    appId: '1:769422548283:android:27d1c89a4ca4b6c4eaab1e',
    messagingSenderId: '769422548283',
    projectId: 'ixo-app-secbizcard',
    storageBucket: 'ixo-app-secbizcard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoH8Y1H4qWg6swS3tL5p1hY_cCsnDw_Qc',
    appId: '1:769422548283:ios:4e890df1eb8a72b4eaab1e',
    messagingSenderId: '769422548283',
    projectId: 'ixo-app-secbizcard',
    storageBucket: 'ixo-app-secbizcard.firebasestorage.app',
    iosBundleId: 'app.ixo.secbizcard',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabQ4XThJ1U5E9LGy_MycldiZRDpEvCOA',
    appId: '1:769422548283:web:297b08d4a714ed98eaab1e',
    messagingSenderId: '769422548283',
    projectId: 'ixo-app-secbizcard',
    authDomain: 'ixo-app-secbizcard.firebaseapp.com',
    storageBucket: 'ixo-app-secbizcard.firebasestorage.app',
    measurementId: 'G-DB9SNW92M6',
  );

}