name: secbizcard
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.3+18

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: 
  firebase_auth: 
  google_sign_in: ^6.2.1 
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  riverpod_annotation: ^2.3.5
  intl: any
  cloud_firestore: ^5.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  font_awesome_flutter: ^10.7.0
  riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.1
  cloud_functions: ^5.6.2
  googleapis: ^15.0.0
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  image: ^4.7.2
  intl_phone_field: ^3.2.0
  email_validator: ^3.0.0
  shared_preferences: ^2.5.4
  equatable: ^2.0.8
  http: ^1.2.0
  package_info_plus: ^9.0.0

  url_launcher: ^6.3.0
  play_install_referrer: ^0.5.0
  image_cropper: ^11.0.0
  firebase_messaging: ^15.2.10
  archive: ^4.0.7
  encrypt: ^5.0.3
  app_links: ^6.4.0
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.3
  uuid: ^4.5.2
  file_picker: ^10.3.10
  camera: ^0.11.3
  google_mlkit_text_recognition: ^0.15.1
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  SecBizCard_OCR:
    path: ../SecBizCard/packages/SecBizCard_OCR

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9 
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.6
  path_provider_platform_interface: ^2.1.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path_ios: "assets/icon/icon_ios.png"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_adaptive_foreground_padded.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#00357a"


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/icon_ios.png
    - assets/icon/icon_adaptive_foreground_padded.png
    - assets/images/logo.svg
    - assets/images/SecBizCard.svg
    - assets/images/google-play-badge.svg
    - assets/images/app-store-badge.svg
    - assets/images/favicon.svg

